<?php

namespace Database\Seeders;

use App\Models\concepto_flujo;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ConceptoFlujoCESeeder extends Seeder
{
    /**
     * Run the database seeds.
     * "ingresos_o_egresos" => date('Y-m-d H:i').'',
     * php artisan db:seed --class=ConceptoFlujoCESeeder
     * php artisan migrate --path=/database/migrations/nombre_de_archivo_migracion.php
     */
    public function run(): void
    {

        concepto_flujo::create(["cuenta_contable" => 511115010, "concepto_flujo" => "Bienes y servicios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Bienes y servicios']);
        concepto_flujo::create(["cuenta_contable" => 511146010, "concepto_flujo" => "Bienes y servicios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Bienes y servicios']);
        concepto_flujo::create(["cuenta_contable" => 511174020, "concepto_flujo" => "Bienes y servicios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Bienes y servicios']);
        concepto_flujo::create(["cuenta_contable" => 511180010, "concepto_flujo" => "Bienes y servicios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Bienes y servicios']);
        concepto_flujo::create(["cuenta_contable" => 720802090, "concepto_flujo" => "Bienes y servicios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Bienes y servicios']);
        concepto_flujo::create(["cuenta_contable" => 720802250, "concepto_flujo" => "Bienes y servicios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Bienes y servicios']);
        concepto_flujo::create(["cuenta_contable" => 240101010, "concepto_flujo" => "Bienes y servicios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Bienes y servicios']);
        concepto_flujo::create(["cuenta_contable" => 249054020, "concepto_flujo" => "Bienes y servicios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Bienes y servicios']);
        concepto_flujo::create(["cuenta_contable" => 720802280, "concepto_flujo" => "Bienes y servicios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Bienes y servicios']);
        concepto_flujo::create(["cuenta_contable" => 720802320, "concepto_flujo" => "Bienes y servicios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Bienes y servicios']);
        concepto_flujo::create(["cuenta_contable" => 511117060, "concepto_flujo" => "Bienes y servicios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Bienes y servicios']);
        concepto_flujo::create(["cuenta_contable" => 511155010, "concepto_flujo" => "Bienes y servicios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Bienes y servicios']);
        concepto_flujo::create(["cuenta_contable" => 511156010, "concepto_flujo" => "Bienes y servicios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Bienes y servicios']);
        concepto_flujo::create(["cuenta_contable" => 720802040, "concepto_flujo" => "Bienes y servicios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Bienes y servicios']);
        concepto_flujo::create(["cuenta_contable" => 720802130, "concepto_flujo" => "Bienes y servicios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Bienes y servicios']);
        concepto_flujo::create(["cuenta_contable" => 510801010, "concepto_flujo" => "Contratistas directos", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Contratistas directos']);
        concepto_flujo::create(["cuenta_contable" => 510801020, "concepto_flujo" => "Contratistas directos", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Contratistas directos']);
        concepto_flujo::create(["cuenta_contable" => 720802020, "concepto_flujo" => "Contratistas directos", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Contratistas directos']);
        concepto_flujo::create(["cuenta_contable" => 720802010, "concepto_flujo" => "Contratistas directos", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Contratistas directos']);
        concepto_flujo::create(["cuenta_contable" => 799010010, "concepto_flujo" => "Contratistas convenios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Ejecución convenios']);
        concepto_flujo::create(["cuenta_contable" => 799010020, "concepto_flujo" => "Contratistas convenios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Ejecución convenios']);
        concepto_flujo::create(["cuenta_contable" => 799002010, "concepto_flujo" => "Gastos desplazamientos convenios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Ejecución convenios']);
        concepto_flujo::create(["cuenta_contable" => 240726191, "concepto_flujo" => "Reintegro rendimientos financieros convenios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Ejecución convenios']);
        concepto_flujo::create(["cuenta_contable" => 799008010, "concepto_flujo" => "Servicios financieros (GMF y comisiones) convenios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Ejecución convenios']);
        concepto_flujo::create(["cuenta_contable" => 799002030, "concepto_flujo" => "Servicios y seguros convenios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Ejecución convenios']);
        concepto_flujo::create(["cuenta_contable" => 799002020, "concepto_flujo" => "Servicios y seguros convenios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Ejecución convenios']);
        concepto_flujo::create(["cuenta_contable" => 799002050, "concepto_flujo" => "Servicios y seguros convenios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Ejecución convenios']);
        concepto_flujo::create(["cuenta_contable" => 799002070, "concepto_flujo" => "Servicios y seguros convenios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Ejecución convenios']);
        concepto_flujo::create(["cuenta_contable" => 290201134, "concepto_flujo" => "Servicios y seguros convenios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Ejecución convenios']);
        concepto_flujo::create(["cuenta_contable" => 799010030, "concepto_flujo" => "Atención humanitaria convenios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Ejecución convenios']);
        concepto_flujo::create(["cuenta_contable" => 290201108, "concepto_flujo" => "Servicios financieros (GMF y comisiones) convenios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Ejecución convenios']);
        concepto_flujo::create(["cuenta_contable" => 290201136, "concepto_flujo" => "Reintegro recursos no ejecutados convenios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Ejecución convenios']);
        concepto_flujo::create(["cuenta_contable" => 290201138, "concepto_flujo" => "Servicios y seguros convenios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Ejecución convenios']);
        concepto_flujo::create(["cuenta_contable" => 290201163, "concepto_flujo" => "Servicios financieros (GMF y comisiones) convenios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Ejecución convenios']);
        concepto_flujo::create(["cuenta_contable" => 290201167, "concepto_flujo" => "Reintegro recursos no ejecutados convenios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Ejecución convenios']);
        concepto_flujo::create(["cuenta_contable" => 290201534, "concepto_flujo" => "Reintegro rendimientos financieros convenios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Ejecución convenios']);
        concepto_flujo::create(["cuenta_contable" => 290201536, "concepto_flujo" => "Reintegro rendimientos financieros convenios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Ejecución convenios']);
        concepto_flujo::create(["cuenta_contable" => 290201547, "concepto_flujo" => "Reintegro rendimientos financieros convenios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Ejecución convenios']);
        concepto_flujo::create(["cuenta_contable" => 290201575, "concepto_flujo" => "Reintegro rendimientos financieros convenios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Ejecución convenios']);
        concepto_flujo::create(["cuenta_contable" => 290201593, "concepto_flujo" => "Reintegro rendimientos financieros convenios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Ejecución convenios']);
        concepto_flujo::create(["cuenta_contable" => 290201731, "concepto_flujo" => "Reintegro rendimientos financieros convenios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Ejecución convenios']);
        concepto_flujo::create(["cuenta_contable" => 290201910, "concepto_flujo" => "Servicios financieros (GMF y comisiones) convenios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Ejecución convenios']);
        concepto_flujo::create(["cuenta_contable" => 439590020, "concepto_flujo" => "Reintegro recursos no ejecutados convenios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Ejecución convenios']);
        concepto_flujo::create(["cuenta_contable" => 799002040, "concepto_flujo" => "Atención humanitaria convenios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Ejecución convenios']);
        concepto_flujo::create(["cuenta_contable" => 799002060, "concepto_flujo" => "Servicios y seguros convenios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Ejecución convenios']);
        concepto_flujo::create(["cuenta_contable" => 799002090, "concepto_flujo" => "Reintegro recursos no ejecutados convenios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Ejecución convenios']);
        concepto_flujo::create(["cuenta_contable" => 799002100, "concepto_flujo" => "Servicios y seguros convenios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Ejecución convenios']);
        concepto_flujo::create(["cuenta_contable" => 799002120, "concepto_flujo" => "Servicios y seguros convenios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Ejecución convenios']);
        concepto_flujo::create(["cuenta_contable" => 799002130, "concepto_flujo" => "Servicios y seguros convenios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Ejecución convenios']);
        concepto_flujo::create(["cuenta_contable" => 799010040, "concepto_flujo" => "Subvenciones y sostenimiento convenios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Ejecución convenios']);
        concepto_flujo::create(["cuenta_contable" => 138490040, "concepto_flujo" => "Traslado de utilidad en la administración de convenios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Ejecución convenios']);
        concepto_flujo::create(["cuenta_contable" => 131701030, "concepto_flujo" => "Traslado de utilidad en la administración de convenios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Ejecución convenios']);
        concepto_flujo::create(["cuenta_contable" => 799008040, "concepto_flujo" => "No suma en flujo", "ingresos_o_egresos" => 'egresos', 'categoria' => 'No suma en flujo']);
        concepto_flujo::create(["cuenta_contable" => 242411010, "concepto_flujo" => "Deducciones empleados / contratistas", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 242404020, "concepto_flujo" => "Deducciones empleados / contratistas", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 242413010, "concepto_flujo" => "Deducciones empleados / contratistas", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 242407090, "concepto_flujo" => "Deducciones empleados / contratistas", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 242408030, "concepto_flujo" => "Deducciones empleados / contratistas", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 242408010, "concepto_flujo" => "Deducciones empleados / contratistas", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 242404010, "concepto_flujo" => "Deducciones empleados / contratistas", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 242407080, "concepto_flujo" => "Deducciones empleados / contratistas", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 242407050, "concepto_flujo" => "Deducciones empleados / contratistas", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 242407020, "concepto_flujo" => "Deducciones empleados / contratistas", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 242407070, "concepto_flujo" => "Deducciones empleados / contratistas", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 242407040, "concepto_flujo" => "Deducciones empleados / contratistas", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 242490020, "concepto_flujo" => "Deducciones empleados / contratistas", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 242405020, "concepto_flujo" => "Deducciones empleados / contratistas", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 242405040, "concepto_flujo" => "Deducciones empleados / contratistas", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 242405060, "concepto_flujo" => "Deducciones empleados / contratistas", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 242408020, "concepto_flujo" => "Deducciones empleados / contratistas", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 242490050, "concepto_flujo" => "Deducciones empleados / contratistas", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 242490040, "concepto_flujo" => "Deducciones empleados / contratistas", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 242490030, "concepto_flujo" => "Deducciones empleados / contratistas", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 138426010, "concepto_flujo" => "Incapacidades y licencias", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 251109050, "concepto_flujo" => "Nómina institucional - Administrativa ", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 251109080, "concepto_flujo" => "Nómina institucional - Administrativa ", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 510101010, "concepto_flujo" => "Nómina institucional - Administrativa ", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 510160010, "concepto_flujo" => "Nómina institucional - Administrativa ", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 510201010, "concepto_flujo" => "Nómina institucional - Administrativa ", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 720803020, "concepto_flujo" => "Nómina institucional - Administrativa ", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 720803022, "concepto_flujo" => "Nómina institucional - Administrativa ", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 720803030, "concepto_flujo" => "Nómina institucional - Cátedra general ", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 251109010, "concepto_flujo" => "Nómina institucional - Docentes planta", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 720803010, "concepto_flujo" => "Nómina institucional - Docentes planta", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 251109060, "concepto_flujo" => "Nómina institucional - Ocasional ", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 720803040, "concepto_flujo" => "Nómina institucional - Ocasional ", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 251101010, "concepto_flujo" => "Prestaciones sociales ", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 251103010, "concepto_flujo" => "Prestaciones sociales ", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 251103050, "concepto_flujo" => "Prestaciones sociales ", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 251104020, "concepto_flujo" => "Prestaciones sociales ", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 510303010, "concepto_flujo" => "Seguridad social", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 720805023, "concepto_flujo" => "Seguridad social", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 720805030, "concepto_flujo" => "Seguridad social", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 720805031, "concepto_flujo" => "Seguridad social", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 720805033, "concepto_flujo" => "Seguridad social", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 720805043, "concepto_flujo" => "Seguridad social", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 720806030, "concepto_flujo" => "Seguridad social", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 799005010, "concepto_flujo" => "Seguridad social", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 251104030, "concepto_flujo" => "Prestaciones sociales ", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 251104050, "concepto_flujo" => "Prestaciones sociales ", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 251102050, "concepto_flujo" => "Prestaciones sociales ", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 251102030, "concepto_flujo" => "Prestaciones sociales ", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 251102010, "concepto_flujo" => "Prestaciones sociales ", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 242401120, "concepto_flujo" => "Deducciones empleados / contratistas", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 242402010, "concepto_flujo" => "Seguridad social", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 242407100, "concepto_flujo" => "Deducciones empleados / contratistas", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 251102040, "concepto_flujo" => "Prestaciones sociales ", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Nómina y seguridad social']);
        concepto_flujo::create(["cuenta_contable" => 511123010, "concepto_flujo" => "Servicios públicos", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 511179010, "concepto_flujo" => "Honorarios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 720801010, "concepto_flujo" => "Insumos y suministros", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 511119010, "concepto_flujo" => "Gastos de viaje y manutención", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 720802050, "concepto_flujo" => "Gastos de viaje y manutención", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 589012010, "concepto_flujo" => "Gestión legal ", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 720802120, "concepto_flujo" => "Movilidad académica", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 512001010, "concepto_flujo" => "Otros egresos", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 720802100, "concepto_flujo" => "Suscripciones, afiliaciones e incripciones", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 512024010, "concepto_flujo" => "Servicios financieros (GMF y comisiones)", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 511117010, "concepto_flujo" => "Servicios públicos", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 511117020, "concepto_flujo" => "Servicios públicos", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 511117030, "concepto_flujo" => "Servicios públicos", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 511117040, "concepto_flujo" => "Servicios públicos", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 511117070, "concepto_flujo" => "Servicios públicos", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 510890010, "concepto_flujo" => "Subvenciones y sostenimiento", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 720802150, "concepto_flujo" => "Subvenciones y sostenimiento", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 190505010, "concepto_flujo" => "Suscripciones, afiliaciones e incripciones", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 720802060, "concepto_flujo" => "Suscripciones, afiliaciones e incripciones", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 439501010, "concepto_flujo" => "Devolución matrículas académicas", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 240706010, "concepto_flujo" => "Seguros ", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 240706140, "concepto_flujo" => "Devolución matrículas académicas", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 240726010, "concepto_flujo" => "Reintegro rendimientos financieros Distrito", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 439501020, "concepto_flujo" => "Reintegros", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 589090010, "concepto_flujo" => "Reintegro rendimientos financieros convenios", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 589501010, "concepto_flujo" => "Reintegros", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 439501130, "concepto_flujo" => "Reintegros", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 720802160, "concepto_flujo" => "Servicios públicos", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 720802170, "concepto_flujo" => "Servicios públicos", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 720802180, "concepto_flujo" => "Servicios públicos", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 720802190, "concepto_flujo" => "Servicios públicos", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 720802200, "concepto_flujo" => "Servicios públicos", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 720802210, "concepto_flujo" => "Servicios públicos", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 720802220, "concepto_flujo" => "Servicios públicos", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 720802260, "concepto_flujo" => "Subvenciones y sostenimiento", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 720802070, "concepto_flujo" => "Subvenciones y sostenimiento", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 511114010, "concepto_flujo" => "Insumos y suministros", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 510803010, "concepto_flujo" => "Suscripciones, afiliaciones e incripciones", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 197008010, "concepto_flujo" => "Suscripciones, afiliaciones e incripciones", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 511125010, "concepto_flujo" => "Seguros ", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 510305010, "concepto_flujo" => "ARL estudiantes y contratistas ", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 511118010, "concepto_flujo" => "Gasto arrendamientos", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 511159010, "concepto_flujo" => "Suscripciones, afiliaciones e incripciones", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 580240010, "concepto_flujo" => "Servicios financieros (GMF y comisiones)", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 720802110, "concepto_flujo" => "Insumos y suministros", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 720802270, "concepto_flujo" => "Seguros ", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 720805050, "concepto_flujo" => "ARL estudiantes y contratistas ", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 240790010, "concepto_flujo" => "Reintegros", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 439590010, "concepto_flujo" => "Reintegros", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 512002010, "concepto_flujo" => "Cuota de fiscalización y auditaje", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Otros egresos']);
        concepto_flujo::create(["cuenta_contable" => 243605060, "concepto_flujo" => "Retenciones en la fuente", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Retenciones e impuestos ']);
        concepto_flujo::create(["cuenta_contable" => 243627020, "concepto_flujo" => "Retenciones en la fuente", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Retenciones e impuestos ']);
        concepto_flujo::create(["cuenta_contable" => 243605010, "concepto_flujo" => "Retenciones en la fuente", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Retenciones e impuestos ']);
        concepto_flujo::create(["cuenta_contable" => 243604020, "concepto_flujo" => "Retenciones en la fuente", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Retenciones e impuestos ']);
        concepto_flujo::create(["cuenta_contable" => 243606010, "concepto_flujo" => "Retenciones en la fuente", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Retenciones e impuestos ']);
        concepto_flujo::create(["cuenta_contable" => 243608010, "concepto_flujo" => "Retenciones en la fuente", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Retenciones e impuestos ']);
        concepto_flujo::create(["cuenta_contable" => 243615010, "concepto_flujo" => "Retenciones en la fuente", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Retenciones e impuestos ']);
        concepto_flujo::create(["cuenta_contable" => 243603020, "concepto_flujo" => "Retenciones en la fuente", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Retenciones e impuestos ']);
        concepto_flujo::create(["cuenta_contable" => 243608020, "concepto_flujo" => "Retenciones en la fuente", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Retenciones e impuestos ']);
        concepto_flujo::create(["cuenta_contable" => 243605050, "concepto_flujo" => "Retenciones en la fuente", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Retenciones e impuestos ']);
        concepto_flujo::create(["cuenta_contable" => 243603010, "concepto_flujo" => "Retenciones en la fuente", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Retenciones e impuestos ']);
        concepto_flujo::create(["cuenta_contable" => 243605020, "concepto_flujo" => "Retenciones en la fuente", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Retenciones e impuestos ']);
        concepto_flujo::create(["cuenta_contable" => 243625010, "concepto_flujo" => "Retenciones en la fuente", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Retenciones e impuestos ']);
        concepto_flujo::create(["cuenta_contable" => 243690030, "concepto_flujo" => "Retenciones en la fuente", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Retenciones e impuestos ']);
        concepto_flujo::create(["cuenta_contable" => 244085020, "concepto_flujo" => "Retenciones en la fuente", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Retenciones e impuestos ']);
        concepto_flujo::create(["cuenta_contable" => 243690040, "concepto_flujo" => "Retenciones en la fuente", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Retenciones e impuestos ']);
        concepto_flujo::create(["cuenta_contable" => 243605030, "concepto_flujo" => "Retenciones en la fuente", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Retenciones e impuestos ']);
        concepto_flujo::create(["cuenta_contable" => 243605040, "concepto_flujo" => "Retenciones en la fuente", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Retenciones e impuestos ']);
        concepto_flujo::create(["cuenta_contable" => 244024010, "concepto_flujo" => "Retenciones en la fuente", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Retenciones e impuestos ']);
        concepto_flujo::create(["cuenta_contable" => 244035010, "concepto_flujo" => "Retenciones en la fuente", "ingresos_o_egresos" => 'egresos', 'categoria' => 'Retenciones e impuestos ']);

    }
}
